### ISSUE TITLE
トップページナビメニューのアニメーション作成

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#10]
左右の矢印をクリックした時に、ちょっといい感じのアニメーションを付けたいです。
一番左右の2つがちょっと小さいサイズで、真ん中5つにはいった時に大きくなるとか、
スライド時は半透明になっていなくて、スライド終了したらふわっと半透明になるとか、
こだわりとかはないので、話し合いつつやりましょう～

**Comment by nss-tomioka** [comment]
とりあえずスライド半透明パターンで作成する。

**Comment by nss-tomioka** [comment]
スライド終了時に半透明になるように修正しました。
https://cpcam.jp/signage_test/

**Comment by nss-shimizu** [comment]
半透明になる、戻る時間はもう少し早くしたいかもですね

**Comment by nss-tomioka** [comment]
半透明になる時間を「.3s→.2s」に修正しました。

**Comment by nss-shimizu** [comment]
OKです。閉じます！
