### ISSUE TITLE
製品ラインアップページ修正

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#11]
- バナーをトル
- H1追加「製品ラインアップ」またはSEO的に「デジタルサイネージ 製品ラインアップ」など
- （下図参照）スマホ時のリンク暴発を防ぐため、下図水色の枠内をクリックした時にジャンプするように修正。これは導入事例一覧や検索結果ページでも同様
- デジタルサイネージの文章「用途に合わせて設置」 -> 「用途に合わせて選択」に変更

![a](https://cloud.githubusercontent.com/assets/10227594/14732630/7027985c-0897-11e6-822b-e821e11adbe8.png)

**Comment by nss-tomioka** [comment]
バナー削除しました。
文章変更済みです。

**Comment by nss-tomioka** [comment]
h1 「デジタルサイネージ 製品ラインアップ」を追加しました。

**Comment by nss-tomioka** [comment]
リンクのブロック要素の範囲をボタンから全体に変更しました。
