### ISSUE TITLE
導入事例の並びをレンガ状に

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#12]
[Masonry](http://allabout.co.jp/gm/gc/402549/)風にタイル？レンガっぽく並べます。
たくさんある感じを出せるかな～と思います。

**Comment by nss-tomioka** [comment]
「Masonry」使ってみました。
https://cpcam.jp/signage_test/case/case.html

**Comment by seseragi7** [comment]
ラインだと区切りが分かりづらいですね～ 笑
かと言って上手いこと背景つける事ができるのかどうか。。。

**Comment by nss-shimizu** [comment]
ラインだと区切りが分かりづらいですね～ 笑
背景の方が良いんでしょうかね～？それかラインをわかりやすくするか。。。

**Comment by nss-tomioka** [comment]
背景色をグレーにしてみました。
