### ISSUE TITLE
画像リンクマウスオーバーの動き

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#13]
画像リンクにマウスオーバーした時の動きを全体で統一します。
なんかアップになったりするやつです。
話し合いながらやりましょう～

**Comment by nss-tomioka** [comment]
導入事例ページの画像に動きをつけてみました。
https://cpcam.jp/signage_test/case/case.html

**Comment by seseragi7** [comment]
いいですね！
もう少し拡大控えめでもいいかもですね！

**Comment by nss-shimizu** [comment]
いいですね！
もう少し拡大控えめでもいいかもですね！

**Comment by nss-tomioka** [comment]
scale(1.2) → scale(1.1) に変更しました。

**Comment by nss-shimizu** [comment]
いいと思います！
画像のリンクにはすべてこれを設定するということで大丈夫ですかね？
大丈夫なようであればIssueを閉じたいと思いますー

**Comment by nss-tomioka** [comment]
了解しました。
この Issue 閉じます。
