### ISSUE TITLE
サポートページのカタログらをリスト状に

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#15]
総合カタログを文化いつして表示するにあたってリスト上のほうが良いと思うので、デザインからやっていきましょう。
画像はこの際必要ないような気もしますが、どうでしょうかね。

**Comment by nss-shimizu** [comment]
また、データサイズ（〇〇MB）の表記も復活させます。

**Comment by nss-tomioka** [comment]
リスト状に修正しました。
アイコンがあった方がスマホのときわかりやすいかなと思ったのですが、どうでしょうか？
製品仕様書のデザインも調整しました。
https://cpcam.jp/signage_test/support/support.html

**Comment by seseragi7** [comment]
サムネがやっぱり欲しいとの要望がありました。
ちょっと高さ増やして、左側に入れましょうか～
前回は確か高さ70pxくらいの画像だったような気がします。

**Comment by seseragi7** [comment]
子要素のL ←こんなやつは必要なくなるかもしれませんね。デザインを見つつ入れるかどうか決めましょう～

**Comment by nss-shimizu** [comment]
サムネがやっぱり欲しいとの要望がありました。
ちょっと高さ増やして、左側に入れましょうか～
前回は確か高さ70pxくらいの画像だったような気がします。

**Comment by nss-shimizu** [comment]
子要素のL ←こんなやつは必要なくなるかもしれませんね。デザインを見つつ入れるかどうか決めましょう～

**Comment by nss-tomioka** [comment]
カタログのサムネイル追加しました。
https://cpcam.jp/signage_test/support/support.html

**Comment by nss-tomioka** [comment]
ボタンを「PDFダウンロード」から「PDFを見る」に変更する。
