### ISSUE TITLE
.htaccess 修正

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#16]
すべてのページで「http -> https」にリダイレクトする。
サブディレクトリ内の「.htaccess」は削除する。

**Comment by nss-tomioka** [comment]
```html
<img class="topic_news_img" src="http://www.cpcam.jp/img/topic_news_arrow.png">
```

こんな感じで、src に http から指定している画像がたくさんあるので、

**Comment by nss-shimizu** [comment]
それ僕も直そうとしたんですけど、多すぎてムリでしたｗ
今回のサイネージリニューアルから、リニューアル時にそういうのを無くすようにしていきたいと思ってます。多すぎて時間掛かるってレベルじゃないので。。。

**Comment by nss-tomioka** [comment]
エラーがいっぱい出てびっくりしました。
リニューアル時に気をつけていきましょう。
