### ISSUE TITLE
トップバナーの動き変更

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#18]
トップページバナーの動きを（スライド以外に）変更したいです。
まだどういう動きにするかはわかりませんが、対応するためにプラグインを制作することになるかもしれません。

**Comment by nss-tomioka** [comment]
クロスフェードスライドショー作成しました。
切り替えの間隔、フェードのスピードなど変更可能です。
スマートフォン時の動きを検討したいです。
https://cpcam.jp/signage_test/

**Comment by nss-tomioka** [comment]
検索結果ページのバナーも同じ CSS、JS を使用できるように修正しました。
https://cpcam.jp/signage_test/product/search.php

**Comment by nss-tomioka** [comment]
スマートフォンに対応させました。
画像の下部にテキストを表示させるように修正しました。
また、スワイプで画像の切り替えができるようにしました。

**Comment by nss-shimizu** [comment]
OKです。閉じます！
