### ISSUE TITLE
詳細ページの関連製品をタブの中から出す

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#19]
タブを

特長｜仕様｜関連製品

ではなく、

特長｜仕様
関連製品

にする。下に常に表示されている

**Comment by nss-tomioka** [comment]
「関連製品」をページの下部に表示するように修正しました。
タイトル部分のデザインは天吊金具のページに合わせています。
http://cpcam.jp/signage_test/product/detail/detail.php

**Comment by nss-shimizu** [comment]
閉じます！
