### ISSUE TITLE
全体の文字色の変更

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#2]
タイトルなどの強調したい所は #333
本文などは #6f6f6f

色は調整しつつ、同じフォントサイズでも少し目立つように

**Comment by nss-tomioka** [comment]
修正しました。
ご確認よろしくお願いします。
http://cpcam.jp/signage_test/

**Comment by nss-shimizu** [comment]
太田主任が作られた新たなデザインに移行する際に、リンクテキストのデザインも変更したいと思っています。
太字で#333でアンダーラインになるかなと思います。
ホバー時は考えられてませんが多分薄くなる感じで良いかと思います。

**Comment by nss-tomioka** [comment]
ホバー時のカラーを「#555」にする。

**Comment by nss-tomioka** [comment]
ホバー時のカラーを「#555」に変更しました。

**Comment by nss-shimizu** [comment]
OKです。閉じます！
