### ISSUE TITLE
お問い合わせボタン類の修正

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#20]
phpで外部から読み込む
お問い合わせボタンを一番左に

**Comment by nss-tomioka** [comment]
「signage_test」フォルダ直下に「_contact.php」を設置しました。
CSSは「base.css」に書いています。
また、お問い合わせボタンを一番左に移動させています。

**Comment by nss-shimizu** [comment]
OKです。閉じます！
