### ISSUE TITLE
フッターの DUNS 変更

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#21]
現在は javascript で DUNS のシールを貼り付けている。
これを画像に変更する。

![nss_duns](https://cloud.githubusercontent.com/assets/18563374/15414360/dae4ed28-1e74-11e6-8692-ddecfbccad5f.jpg)

**Comment by nss-tomioka** [comment]
DUNS シールのリンク先が ASP で書かれているため、直でリンクできません。
メール用のリンクを使っても良いのでしょうか？

https://profiles.dunsregistered.com/DunsRegisteredProfileAnywhere.aspx?key1=3098677&PaArea=mail

何か同意しないと見れない感じですが。。。

**Comment by nss-tomioka** [comment]
メール用のリンクを使用する。

**Comment by nss-tomioka** [comment]
メール用のリンクを使用した画像に修正しました。

**Comment by nss-tomioka** [comment]
画像サイズを小さくしました。

**Comment by nss-shimizu** [comment]
DUNSが目立たないように、なんかこの辺においてみようか的な感じの案が出ました。
背景が白いので今よりは目立たなくなるかと思います。これで違和感なければ採用したいです。

![2](https://cloud.githubusercontent.com/assets/10227594/17693074/1f2057e0-63d8-11e6-8a1d-1919e28732f1.png)

**Comment by nss-tomioka** [comment]
DUNS の位置を修正しました。
以前よりは目立たなくなったような気がします。

**Comment by nss-shimizu** [comment]
OKです。閉じます！
