### ISSUE TITLE
ボタンがある場合のリンク範囲を修正

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#24]
ボタンがある場合は、リンクのブロック要素の範囲をボタンのみにする。
スマートフォン時に間違ってタップしないようにするため。

- 製品ラインアップページ

- サポートページ

**Comment by nss-tomioka** [comment]
「製品ラインアップページ」修正しました。

**Comment by nss-tomioka** [comment]
「サポートページ」修正しました。
https://cpcam.jp/signage_test/support/support.html

**Comment by nss-shimizu** [comment]
やっぱり元の、一番外側のちょっと内側をリンクにします。
ラインアップページだけです。サポートはそのままでよいと思います。

**Comment by nss-tomioka** [comment]
ラインアップページ修正しました。

**Comment by nss-shimizu** [comment]
ラインアップページなんですが、
・説明のテキスト 青→黒に

あと、これどうなのか迷ってるんですが、
・タイプ名「デジタルサイネージ」とその英語表記に、マウスオーバーでアンダーライン
PC版だとどうしてもボタンだけ押せそうな感じがするので、分かりやすいかなーと思ったんですけどどうでしょうか。

**Comment by nss-tomioka** [comment]
マウスオーバー時にアンダーラインを付けるように修正してみましたが、どうでしょうか？
https://cpcam.jp/signage_test/product/product.html

**Comment by nss-shimizu** [comment]
良いんじゃないでしょうか！
一旦閉じます！
