### ISSUE TITLE
画像リンクのホバー時の動きがおかしい

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#25]
画像リンクのホバー時に拡大するようにしているが、他の画像の動きがおかしい。要調査。

**Comment by nss-tomioka** [comment]
Chrome のみで 1px ずれるバグでした。
backface-visibility プロパティを使用することで回避できました。

`-webkit-backface-visibility: hidden;`
`backface-visibility: hidden; `

参考にしたサイト
[【CSS】transitionプロパティ使用時に、Chromeブラウザで1pxずれる現象を回避する](http://bashalog.c-brains.jp/14/02/03-144700.php)

**Comment by nss-tomioka** [comment]
Firefox で確認したところ、Firefox のみでホバー時に画像が一瞬ちらつく現象が発生。
「will-change」プロパティを使用するように修正しました。

`will-change: transform;`

参考にしたサイト
[will-change](https://developer.mozilla.org/ja/docs/Web/CSS/will-change)

**Comment by nss-shimizu** [comment]
OKかな？閉じます！
