### ISSUE TITLE
トップページへ戻るがずれるバグ

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#27]
画像にマウスオーバーして拡大させているときに、右下のトップへ戻るがずれたり震えたり？する。
太田主任のPCで確認。清水PCでは再現できず。

何か原因っぽい作りがあるか検証。

**Comment by nss-tomioka** [comment]
これって導入事例一覧ページのことですよね？
私のPCで再現しましたので、修正します。

**Comment by nss-tomioka** [comment]
Chrome のみで発生するバグです。
#25 と関連しそうです。
調べた結果、CSSで画像を拡大したときにずれが発生していました。

> transform: scale(1.1);

解決するために、画像のホバー時にCSSではなく、javascriptで画像を拡大するように修正しました。

**Comment by nss-shimizu** [comment]
OKです。閉じます！
