### ISSUE TITLE
ショールームページ作成

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#28]
ショールームページを作成する。
現在は東京営業所のみですが、本社と全営業所の内容を見れるようにする。
展示されている製品やコンテンツがわかるようにする。

**Comment by nss-tomioka** [comment]
とりあえず、本社タブのみ作成しました。
画像はクリックで拡大表示するようにしています。
https://cpcam.jp/signage_test/showroom/showroom.html

**Comment by nss-shimizu** [comment]
いい感じだと思います。
バナーを仮のものでもいれてみたいですね、あと、お問い合わせのパーツのデザインが若干崩れてるので、そこも修正したいです。

**Comment by nss-shimizu** [comment]
あと、タイトル下のテキスト「ぜひお気軽にご利用ください。」を「ぜひお気軽にお問い合わせください。」にしたらどうでしょうかね。

**Comment by nss-tomioka** [comment]
タイトル部分を削除し、バナーを表示するように修正しました。
また、テキストも修正しています。

**Comment by nss-tomioka** [comment]
お問い合わせ部分のデザインを修正しました。

**Comment by nss-shimizu** [comment]
ショールームページ修正のIssueがあるので綴じますね
