### ISSUE TITLE
トップページ完成に向けて

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#29]
1つずつページを完成させていこうということで、まずはトップページから完成させようと思います。
現段階で出ている改善点をここに書いていきます。実際に見せれる形まで持っていく予定なので、気になったことがあったら書いていってください～。

【バナー】
・テキストを本番用に
・iPhone時のテキストをイマージの上にかぶせ、下には置かないように変更
　その際、テキストの最大量を決めて、テキストの量で高さが変わらないようにできればよい

【ヘッダー・フッター】
・iPhone時のヘッダーのテキストを押しやすく
・フッターの「>」を「+」と「-」に（すぐ上にトップへ戻るボタンがあり違和感があるので）
・iPhone時のフッターは最初全て閉じておく

**Comment by nss-tomioka** [comment]
バナー修正しました。
スマートフォン時には画像上にテキストをかぶせるようにしました。
また、テキストは未調整ですが、テキストの最大量からバナーの大きさを変更するように修正しました。

**Comment by nss-tomioka** [comment]
スマートフォン時のヘッダーのテキストの上下 padding を「6px→9px」に変更しました。
また、フッター部分の「>」アイコンを「+」と「-」に変更しました。

**Comment by nss-shimizu** [comment]
ヘッダーとフッターの部分は、もう少し押しやすく出来ないですかね～。。。
あと、ヘッダーフッターのグレーの文字はもう少し明るくしましょうか。流石に暗すぎる気がします 笑

**Comment by nss-tomioka** [comment]
スマートフォン時のフッターを全て閉じておくように修正しました。
また、ヘッダーとフッターのフォントサイズ、色、余白を微調整しました。
まだ押しにくいですかね？

**Comment by nss-tomioka** [comment]
トップページの新着情報部分は現状、HTMLに直で書いています。
DBから引っ張ってくるのを忘れないようにしましょう。

**Comment by nss-tomioka** [comment]
トップページの新着情報をDBから取得するようにしました。
現在は全件表示していますが、最大10件などのように制限した方が良いでしょうか？
その場合、現在のサイトのように別ページで一覧を表示するような感じになると思いますが・・・
http://cpcam.nss-server.net/signage_test/

**Comment by nss-tomioka** [comment]
あと、気になったのはDBから取得したリンク先が現在のサイトのリンク先になっていることです。

```html
<a href="https://cpcam.jp/signage/product/player/1000series/nstb-1135.html">NSTB-1135</a>の販売を終了しました。後継機種として<a href="https://cpcam.jp/signage/product/player/1000series/nstb-1136.html">NSTB-1136</a>の販売を開始しました。
```

```
https://cpcam.jp/signage/product/player/1000series/nstb-1135.html
```
↑このフォルダ構成って変わりますよね？

**Comment by nss-shimizu** [comment]
変わりますが、とりあえず404があるのでそれで対応しようかなーと思ってますｗ
