### ISSUE TITLE
検索結果ページ 「NEW」「近日発売」などが同じ色になっている

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#30]
SignageSearchAjax.php の 150行目あたりで
`class="srh-icon-new"`
になっているので、class を振り分けてください。

```
<?php
if( $val['notice'] != '' ):
?>
<span class="srh-icon-new"><?= $val['notice']; ?></span>
<?php
endif;
?>
```

class 名

* NEW : srh-icon-new
* 在庫限り : srh-icon-limited
* 近日発売: srh-icon-soon
* 保留 : srh-icon-wait
* 販売終了: srh-icon-out

**Comment by nss-shimizu** [comment]
↑修正してます～。
