### ISSUE TITLE
デジタルサイネージの詳細ページでサイズを選択できるようにする

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#32]
amazon みたいな感じで、詳細ページでディスプレイサイズの切り替えができるようにする。

**Comment by nss-tomioka** [comment]
ディスプレイサイズを選択できるようにしました。
https://cpcam.jp/signage_test/product/detail/detail.php

**Comment by nss-tomioka** [comment]
ボタンがリンクになるため、文字色を「青」→「黒」にする。

**Comment by nss-tomioka** [comment]
↑ CSSを修正しています。

**Comment by nss-shimizu** [comment]
OKです。閉じます！
