### ISSUE TITLE
詳細ページ 「関連製品」のタイトルデザイン変更

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#33]
「関連製品」のタイトルをグレー背景から border-top のデザインに変更する。
また、フォントサイズも調整する。

**Comment by nss-tomioka** [comment]
デザイン修正しました。
レスポンシブに対応させています。
https://cpcam.jp/signage_test/product/detail/detail.php

**Comment by nss-tomioka** [comment]
「関連製品」のタイトルのフォントサイズを大きくしてみました。
`font-size: 20px;`

**Comment by nss-shimizu** [comment]
OKだと思いますので、このIssueは閉じます！
