### ISSUE TITLE
特長テンプレート デザイン修正

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#34]
詳細ページの特長部分を読みやすいデザインに修正する。
また、余白を調整する。

**Comment by nss-tomioka** [comment]
簡易型デジタルサイネージ
https://cpcam.jp/signage_test/product/detail/test_special_template/12.php

**Comment by nss-tomioka** [comment]
h1 下の余白調整しました。

**Comment by nss-tomioka** [comment]
拡張型デジタルサイネージ（ロータイプ）
https://cpcam.jp/signage_test/product/detail/test_special_template/8.php

**Comment by nss-tomioka** [comment]
拡張型デジタルサイネージ（壁掛タイプ）https://cpcam.jp/signage_test/product/detail/test_special_template/9.php

**Comment by nss-tomioka** [comment]
拡張型デジタルサイネージ（キオスクタイプ）
https://cpcam.jp/signage_test/product/detail/test_special_template/6.php

**Comment by nss-tomioka** [comment]
拡張型デジタルサイネージ（壁掛タイプ・屋外）
https://cpcam.jp/signage_test/product/detail/test_special_template/10.php

**Comment by nss-tomioka** [comment]
拡張型デジタルサイネージ（キオスクタイプ・屋外）
https://cpcam.jp/signage_test/product/detail/test_special_template/7.php

**Comment by nss-tomioka** [comment]
タッチパネルデジタルサイネージ（壁掛タイプ・屋内）
https://cpcam.jp/signage_test/product/detail/test_special_template/17.php

**Comment by nss-tomioka** [comment]
タッチパネルデジタルサイネージ（キオスクタイプ・屋内）
https://cpcam.jp/signage_test/product/detail/test_special_template/15.php

**Comment by nss-tomioka** [comment]
タッチパネルデジタルサイネージ（壁掛タイプ・屋外）
https://cpcam.jp/signage_test/product/detail/test_special_template/18.php

**Comment by nss-tomioka** [comment]
タッチパネルデジタルサイネージ（キオスクタイプ・屋外）
https://cpcam.jp/signage_test/product/detail/test_special_template/16.php

**Comment by nss-tomioka** [comment]
h2 色変更しました。
#333 → #555

**Comment by nss-tomioka** [comment]
タッチパネルの特長から「デジタルサイネージ用PC」ボタンを削除し、テキストにリンクを付けるように修正しました。
https://cpcam.jp/signage_test/product/detail/test_special_template/17.php

**Comment by nss-tomioka** [comment]
フルHDの特長など、2カラムにできるところはレイアウトを修正しています。

**Comment by nss-tomioka** [comment]
500シリーズメディアプレーヤー
https://cpcam.jp/signage_test/product/detail/test_special_template/5.php

**Comment by nss-tomioka** [comment]
1000シリーズ メディアプレーヤー
https://cpcam.jp/signage_test/product/detail/test_special_template/2.php

**Comment by nss-tomioka** [comment]
1000シリーズ メディアプレーヤー
https://cpcam.jp/signage_test/product/detail/test_special_template/4.php

**Comment by nss-shimizu** [comment]
H2とH3の違いがよくわからないという話をされてました。

500シリーズは無くなりますが、これで説明しますと、
「1.テンプレートで簡単にコンテンツ作成」と、「テンプレートを選択」の違いということですね。
無彩色だけじゃなくて色も使うなら使っていいよとのことでした。

![1](https://cloud.githubusercontent.com/assets/10227594/17692668/f6bdeaf8-63d5-11e6-8349-5d2f0edfbbc6.png)

**Comment by nss-tomioka** [comment]
1000シリーズ 中央管理サーバー
http://cpcam.nss-server.net/signage/product/detail/test_special_template/1.php

**Comment by nss-tomioka** [comment]
デジタルサイネージ用PC
http://cpcam.nss-server.net/signage/product/detail/test_special_template/11.php

**Comment by nss-tomioka** [comment]
SuperReporter2
http://cpcam.nss-server.net/signage/product/detail/test_special_template/14.php

**Comment by nss-tomioka** [comment]
SuperMonitor4
http://cpcam.nss-server.net/signage/product/detail/test_special_template/13.php

**Comment by nss-tomioka** [comment]
h3 のデザインを修正しました。
特長テンプレートで h3 の見出しを使用しているのは 500シリーズのメディアプレーヤーのみです。
http://cpcam.nss-server.net/signage/product/detail/test_special_template/5.php

**Comment by nss-shimizu** [comment]
一旦OKです。閉じます！
