### ISSUE TITLE
サポートページ修正

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#35]
・サイネージカタログの項目別ダウンロードをたたむ
「株式会社NSSデジタルサイネージ製品総合カタログ 2016 Vol.1（全ページ）」の行の下に
「項目ごとにダウンロード」等のテキストを入れ、アンダーラインなどで押せるような感じを出す。
そこを押したらスライドダウンで出てくる感じ。
背景のグレーはマウスオーバー時にする？

・ボタンの変更
ボタンのアイコンを取り、【PDF（13.5MB）】というふうな表記にする。

**Comment by nss-tomioka** [comment]
修正しました。
「項目ごとにダウンロード」のテキストには「+」とかアイコン付けた方が良いでしょうか？
http://cpcam.nss-server.net/signage/support/support.html

**Comment by nss-shimizu** [comment]
「項目ごとにダウンロード」は+を付けるタイプのものにしましょうか。リンク感のないものがいいですね。

あと、
・タブに「販売終了製品」と「販売店書類」を足す
・スマホ時のタブのデザインを（既になってるかもしれないけど）ショールームのタブと同じにする
・「カタログ/パンフレット」を「カタログ」に
・総合カタログのborder-topは取る

**Comment by nss-tomioka** [comment]
上記の修正しています。
製品仕様書と販売終了製品のリンクはまだ付けていません。

**Comment by nss-shimizu** [comment]
「項目ごとにダウンロード」は周りを囲うか、ボタン感のあるものにしたいです。
場所は同じでかまいません。

**Comment by nss-tomioka** [comment]
「項目ごとにダウンロード」をボタンに変更しています。

**Comment by nss-shimizu** [comment]
OKです。閉じます～。
