### ISSUE TITLE
ショールームページ修正

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#36]
・上のバナー削除
・サポートページのように、タイトル、英語タイトル、テキストの流れにする。
・セキュリティとデジタルサイネージの項目を合わせる
・各ショールームの項目の順番は、

「見出し」
「セキュリティサイネージ合わせたテキスト」
「セキュリティサイネージ合わせた画像」
「展示されている製品」

・お問い合わせの所は詳細ページみたく線で区切っていいかも？？

**Comment by nss-tomioka** [comment]
修正しました。
展示されている製品はリンクにした方が良いでしょうか？
http://cpcam.nss-cloud.net/signage/showroom/showroom.html

**Comment by nss-shimizu** [comment]
写真のライトボックスに✕ボタン、スマホ時にも＜＞を付けるようにします。

**Comment by nss-tomioka** [comment]
lightbox に「×」と「<>」ボタンを付けるように修正しました。

**Comment by nss-shimizu** [comment]
OKです。閉じます～。
