### ISSUE TITLE
新サーバーへデータ移行

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#39]
cpcam.jp/signage_test/　→　cpcam.nss-cloud.net/signage/ へデータを移行する。
最終的には http://cpcam.jp/signage/ に変更になります。

**Comment by nss-tomioka** [comment]
新サーバーへ移行しました。

**Comment by nss-tomioka** [comment]
本番用Webサーバーのドメインに変更しました。
http://cpcam.nss-server.net/signage/

**Comment by nss-tomioka** [comment]
サイネージのフォルダ名を「signage_test」に戻しました。
http://cpcam.nss-server.net/signage_test/

**Comment by nss-shimizu** [comment]
OKです。閉じます！
