### ISSUE TITLE
製品詳細ページに「NEW」などのアイコンを入れる

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#42]
製品詳細ページに「NEW」などのアイコンを入れるデザインを作っていなかったので作成しました。
品番の横に表示するようにしています。
https://cpcam.jp/signage_test/product/detail/nsmp-4700.html

_detail_base.php の 103行目あたりに入れています。
この部分をPHPで読み込むようにしてください。

```html
<div class="det-icon-box"><span class="srh-icon srh-icon-new">NEW</span></div>
```

**Comment by nss-shimizu** [comment]
PHPで読み込むようにしました。
