### ISSUE TITLE
製品検索時に同じ製品が2つ表示される

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#43]
ヘッダーフォームからの製品検索で「4203t」と検索すると、
検索結果に「NSMP-4203T」が2つ表示される。

たぶん、デジタルサイネージの拡張型とタッチパネルのタブのところが関係しているような気がします。
修正お願いします。

**Comment by nss-shimizu** [comment]
割と修正しづらいタイプのやつですね...。
今後2つのタイプをまたぐものが出てこないならいいんですが、ちょっと考えないといけないですね～。

**Comment by nss-shimizu** [comment]
一旦閉じます。
