### ISSUE TITLE
検索結果の絞り込み検索を最初から表示する

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#44]
![1](https://cloud.githubusercontent.com/assets/10227594/18501050/98c3e35c-7a88-11e6-9fd7-b599c274b2f0.png)

イメージこんな感じです

**Comment by nss-shimizu** [comment]
また、スマホは最初閉じておく今までのものになります。
その時、「今何を検索しているか」を表示したいです。（品番検索のように）

**Comment by nss-tomioka** [comment]
↑修正しています。
「search.php」チェックインしています。

**Comment by nss-tomioka** [comment]
ちょっとお願いしたいことがあるのですが、
検索項目の「ディスプレイサイズ」のチェックボックス部分をDBから取得するようにして欲しいです。

現在は「search.php」に直にタグで書いていますが、
「デジタルサイネージ」で使用しているインチ数、「ディスプレイ」で使用しているインチ数みたいな感じで。
「ディスプレイ」だと色々なサイズが出てきて、メンテナンスするのが大変そうなので。
時間があるときで良いので、よろしくお願いします。

**Comment by nss-shimizu** [comment]
↑修正しています。
一旦閉じますね。
