### ISSUE TITLE
その他細かな修正 - 9/21追加分

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#45]
■トップページ
・右下の順番を変更
・iPhone時のナビメニューを太字＆アンダーラインに

■検索結果ページ
・オプションは下に続けるのでなく、タブに
・品番検索時はバナーなし、パンくずとプレースホルダを「品番検索」に

■フッター
iPad、iPhone時のフッターが大きめなので、他のボタンやタブに大きさを合わせる

**Comment by nss-shimizu** [comment]
![1](https://cloud.githubusercontent.com/assets/10227594/18697437/164e2b84-7ffc-11e6-95c5-e29351530e0f.png)
「new」等のアイコンのCSSをposition: absolute;にしてください。無いものとあるものでのズレが出ないようにしたいです。画像に被って大丈夫です。

また、左の画像にパディングが設定されてますが、どこでその設定がされているかわかりますか？js側のようです。これで画像が小さくなって、大きさが変わってるように見えているっぽいです。

**Comment by nss-tomioka** [comment]
placeholder を「品番検索」に変更しています。

**Comment by nss-tomioka** [comment]
スマートフォン時のナビメニューを太字＆アンダーラインに修正しています。

**Comment by nss-tomioka** [comment]
■トップページ
・右下の順番を変更

↑これってどの部分のことですか？

**Comment by nss-tomioka** [comment]
タブレット、スマートフォン時のフッターの大きさを調整しています。

**Comment by nss-shimizu** [comment]
■トップページ
・右下の順番を変更

![1](https://cloud.githubusercontent.com/assets/10227594/18826082/8a8b2390-8406-11e6-88b0-f16d75e7f62f.png)

これのことですー
現在左上から、問い合わせ→導入事例→ソリューション→カタログ→販売店募集→採用情報となっているのを、
導入事例→ソリューション→カタログ→販売店募集→採用情報→問い合わせに一旦変更したいです。
再度変更があるかもしれません。

**Comment by nss-tomioka** [comment]
↑ 順番変更しています。

**Comment by nss-tomioka** [comment]
画像に padding が設定されているため、画像が小さく表示される不具合を修正しました。
padding → margin に変更しています。
https://cpcam.jp/signage_test/product/search.php?cty=display_1

**Comment by nss-tomioka** [comment]
品番検索時のパンくずを「品番検索」に変更しています。

**Comment by nss-tomioka** [comment]
品番検索で空文字が検索された場合、action を通さないように javascript 側で制御するようにしています。

**Comment by nss-shimizu** [comment]
iPadiPhone時のフッター、もう少し小さくてもよいと思います。
右上のハンバーガーメニューの大きさ、余白感とあわせて、「+」をもう少し小さくしたいですね。

あとトップへ戻るの場所ですが、気持ち的にはそれらのアイコンとX軸揃えたいですが、右にピッタリ付くのはそれはそれで気持ち悪いので、付かない程度に右に寄せたいです。

**Comment by nss-tomioka** [comment]
↑修正しています。
