### ISSUE TITLE
詳細ページのディスプレイサイズがおかしい

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#48]
詳細ページのディスプレイサイズ「55型」が被っています。
動きもおかしいです。
LFVシリーズに55型が複数あるからでしょうか？
https://cpcam.jp/signage_test/product/detail/th-55lfv6j.html

**Comment by nss-shimizu** [comment]
そうみたいですね。同じシリーズ同じインチ数だとこうなるっぽいです。
IDとかで判断させるとかもできますが、「同じもののインチ違い」という概念から行くと、別のシリーズにしたほうが良いでしょうね～
