### ISSUE TITLE
絞り込み検索修正

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#50]
検索結果の絞り込み検索についての修正です。
・絞り込み検索はブロックではなくインラインで各項目を表示。その際項目ごとに「span display:inline-block」などで囲むなどして、途中で改行されないようにする。

**Comment by nss-tomioka** [comment]
↑修正しています。

**Comment by nss-shimizu** [comment]
↑ ありがとうございます～

![1](https://cloud.githubusercontent.com/assets/10227594/19994781/dd47a9f8-a294-11e6-8c01-b56fac6289f8.png)
絞り込みの項目部分、最低幅を決めるかなんかで、段のズレをなくしたいですね。

また、絞り込み検索が外に出ているときは、今これで検索してますの表示をOFFにしたいです。

**Comment by nss-tomioka** [comment]
壁掛金具とディスプレイスタンドの絞り込み項目「対応ディスプレイサイズ」のデザインを修正する。
テキストフィールドの上下ボタンを消す。

**Comment by nss-tomioka** [comment]
↑修正しています。

**Comment by nss-shimizu** [comment]
OKです！閉じます
