### ISSUE TITLE
ショールームページのタブ、active情報をパラメータで保存

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#53]
＞ショールームページで
例えば東京営業所の「現在展示中の製品」の製品をクリックすると製品詳細ページに飛びますが、他の展示製品もみたいと思い前のページにブラウザの戻るボタンで戻るとタブが本社に戻ってしまいます。可能であれば東京営業所のタブを選択した状態のページ戻れるといいのですが。

タブの情報をアドレス欄のパラメータに保存（？）しておき、ブラウザバックで目的のタブが開いた状態に戻れるようにしたいです。

**Comment by nss-tomioka** [comment]
修正しています。

**Comment by nss-shimizu** [comment]
OKです。閉じます
