### ISSUE TITLE
対応インチ数検索にクリアボタンを付ける

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#55]
ディスプレイスタンド、壁掛け金具のところにある対応インチ検索ですが、クリアしたくてもできないので、そのボタンが欲しいです。
挙動としては、インチ数の値を消去→Ajax検索みたいな感じで、全部の製品が出ればOKです

**Comment by nss-tomioka** [comment]
修正しています。
https://cpcam.jp/signage_test/product/search.php?cty=stand_1

**Comment by nss-shimizu** [comment]
OKです。閉じます！
