### ISSUE TITLE
お問い合わせパーツ改善

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#57]
お問合わせはこちらのパーツの電話番号等が目立ちすぎるので、フォームへのボタンを目立たせて電話番号なんかはちょろっと書く感じでいきたいです。
![a](https://cloud.githubusercontent.com/assets/10227594/20995217/e6e1cfd4-bd38-11e6-990f-980b088ebc54.png)

**Comment by nss-tomioka** [comment]
フォントサイズ調整しています。
また、各ページのフッターにお問い合わせのパーツを追加しています。
フッターはヘッダーと同様に _common.php と _signage.php に分けています。

**Comment by nss-shimizu** [comment]
こっちあったのに新しいとこに書いてすみません！
閉じます！
