### ISSUE TITLE
ページ移行

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#6]
本番環境へページ移行

**Comment by nss-tomioka** [comment]
「index.html」 移行しました。
https://www.cpcam.jp/signage_test/index.html

**Comment by nss-shimizu** [comment]
りょうかいです！
アドレス今後httpsで良いかもしれませんねー速さ変わらないし

**Comment by nss-tomioka** [comment]
「product.html」 移行しました。
https://www.cpcam.jp/signage_test/product/product.html

**Comment by nss-tomioka** [comment]
「case.html」 移行しました。
https://www.cpcam.jp/signage_test/case/case.html

**Comment by nss-tomioka** [comment]
「support.html」 移行しました。
https://www.cpcam.jp/signage_test/support/support.html

**Comment by nss-tomioka** [comment]
「404.html」 移行しました。
https://www.cpcam.jp/signage_test/404.html

**Comment by nss-tomioka** [comment]
「signage_test/.htaccess」に404エラーページを設定しました。

**Comment by nss-tomioka** [comment]
「search.php」 移行しました。
https://cpcam.jp/signage_test/product/search.php?cty=simple
