### ISSUE TITLE
導入事例一覧のレスポンシブデザイン

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#60]
スマホよりちょっと大きいくらいの幅で導入事例一覧ページを見ると、グレーの背景は幅100%で、写真は左よりになっています。また、マウスオーバーで写真が縮小します。

1カラムになった段階で写真は常に最大表示にしましょうか？画像の縮小に関する動きはバグかと思いますが、そちらも直したいです。

**Comment by nss-tomioka** [comment]
修正しています。
https://cpcam.jp/signage_test/case/
