### ISSUE TITLE
フッター余白調整

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#64]
ラインアップページなど、各ページ内で違和感のない余白に設定する
![1](https://cloud.githubusercontent.com/assets/10227594/21374367/9217c43c-c769-11e6-96a5-62813215c981.png)
ラインの上をちょっと増やして、お問い合わせパーツの下をちょっと減らすような感じでいいかと思います。
![2](https://cloud.githubusercontent.com/assets/10227594/21374377/b5b70ab0-c769-11e6-98b2-4a44799fdf30.png)
こっちは今も違和感ないですが、全体の統一余白にしてみてそちらで違和感がなかったら余白を統一しましょうか。

**Comment by nss-tomioka** [comment]
修正しました。
余白統一しています。

**Comment by nss-shimizu** [comment]
ありがとうございます。ラインの上は70pxくらいあってもいいかなと思ったんですけど、どうですかね？
あとこれはトップページも含めて置くんでしたっけ。

**Comment by nss-tomioka** [comment]
70px に修正しました。
サイネージのフッター全部にということでしたので、トップページにも設置しています。
