### ISSUE TITLE
お問い合わせページ

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#66]
瀧さんの気づいた点を元に修正案を出してみました。

・入力欄に入力した時の文字色を#333に。プレースホルダとの差を付けるためです。

・テキストボックスの上下の余白をもう少し広く。
「未入力や誤入力による警告文が一つ上の入力欄と重なって入力しづらくなっている」とのことでした。
![3](https://cloud.githubusercontent.com/assets/10227594/21382966/c4938cba-c7a6-11e6-81f0-cd86729f23e9.png)
20px→30pxにしてみましたけどどうですかね？変かな？

・iPhoneでクローム、firefox、safariを使用時、業種詳細の業種名が下の罫線とかぶって表示されるのを修正
![b33c96f7a20ce73a11936fe1ad81b8dc0365a58eef3e8605d1 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/10227594/21383038/0f3deeb8-c7a7-11e6-8976-f82c1f42c3ac.jpg)
こうなってるっぽいです。僕の書き方が悪かった感じします。

以上、随時宜しくお願いします。

**Comment by nss-tomioka** [comment]
テキストボックスの文字色を#333 へ変更しています。
サイネージのテキストボックスも同様に修正しています。

**Comment by nss-tomioka** [comment]
↑ 修正しています。

**Comment by nss-shimizu** [comment]
OKです。閉じます～
