### ISSUE TITLE
細かな修正（CSS）

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#68]
・フッターのDUNS、左からの位置をコンテンツと合わせる。（左にマージン、パディングを取る）
・iPadのときはヘッダーを開く（総合ヘッダーは開いてないっぽい？）

**Comment by nss-shimizu** [comment]
![1](https://cloud.githubusercontent.com/assets/10227594/21665085/e9471b02-d32d-11e6-8ea6-f877a44dfe7e.png)
トップの新着にある矢印、activeと通常を逆にしたほうが見やすいですかね？

**Comment by nss-takano** [comment]
上記新着情報の矢印を変更しております。

**Comment by nss-tomioka** [comment]
ヘッダー、フッター部分の修正しています。

**Comment by nss-shimizu** [comment]
OKです。閉じますね
