### ISSUE TITLE
導入時のポイントを入れる

### ISSUE THREAD

**Issue by nss-tomioka** [NSS-web/Signage-site#71]
ソリューションの「NSSデジタルサイネージの種類と特徴」ページ
「タッチパネルデジタルサイネージ + デジタルサイネージ用PC（ネットワーク）」の部分に導入時のポイントを入れる。
https://cpcam.jp/signage_test/solution/sol-type.html

**Comment by nss-tomioka** [comment]
導入時のポイントを追加しています。

**Comment by nss-shimizu** [comment]
ありがとうございます。
ちょっと修正しました。閉じますね
