### ISSUE TITLE
全体の幅の調整

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#8]
ヘッダーやバナー以外のコンテンツ幅を1280 -> 1200に修正します。
iPadよりも小さいサイズの時は15pxでこれまでと変わりありません。

**Comment by nss-shimizu** [comment]
その際のトップページでの、新着情報と右の6つのコンテンツの間はいい感じにあわせてください～

**Comment by nss-tomioka** [comment]
サポートページのコンテンツ幅を1280 -> 1200に修正しました。
https://cpcam.jp/signage_test/support/support.html

**Comment by nss-tomioka** [comment]
導入事例のコンテンツ幅を1280 -> 1200に修正しました。
https://cpcam.jp/signage_test/case/case.html

**Comment by nss-tomioka** [comment]
製品ラインアップのコンテンツ幅を1280 -> 1200に修正しました。https://cpcam.jp/signage_test/product/product.html

**Comment by nss-shimizu** [comment]
ここまで確認してますOKです～

**Comment by nss-tomioka** [comment]
トップページのコンテンツ幅を1280 -> 1200に修正しました。
https://cpcam.jp/signage_test/

**Comment by nss-tomioka** [comment]
検索結果ページのコンテンツ幅を1280 -> 1200に修正しました。
https://cpcam.jp/signage_test/product/search.php?cty=simple
