### ISSUE TITLE
細かな修正

### ISSUE THREAD

**Issue by nss-shimizu** [NSS-web/Signage-site#9]
#### ヘッダー
- 総合ヘッダーの各ボタン間のライン「｜」を取る

#### バナー
- 左右の「＜」「＞」は色によって見えづらくなるため、黒い四角の中に白抜きで＜＞を配置するようにします。
- バナー下のまるぽちはアクティブ時になにかしら色を付けるようにします。[apple](http://www.apple.com/jp//?afid=p238%7CsKSMckWTz-dc_mtid_18707vxu38484_pcrid_78978864621_&cid=aos-jp-kwg-brand-slid-)参照

**Comment by nss-tomioka** [comment]
総合ヘッダーの各ボタン間のライン「｜」を取りました。

**Comment by nss-tomioka** [comment]
バナーの「＜」「＞」の色を黒ベースに修正しました。
ページャーのアクティブ時の色をサイネージの緑「#008880」に変更しました。
ちょっと見えにくいような気もしますが、ご確認お願いします。
https://cpcam.jp/signage_test/
